[env]
framework = arduino
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.2.1
	paulstoffregen/Encoder@^1.4.4
	https://github.com/adafruit/Adafruit_NeoPixel.git
	https://github.com/bogde/HX711.git
	EEPROM
	olikraus/U8g2@^2.36.2
	https://github.com/tuptusstokrotka/FastButtons.git
	https://github.com/mike-matera/ArduinoSTL.git
build_flags =
	-I include
	-std=c++17
	-std=gnu++17
	-fno-exceptions
	-fno-rtti
build_unflags =
	-std=gnu++11

; [env:nanoatmega328]
; platform = atmelavr
; board = nanoatmega328		; chinese usb-c
; build_flags =
; 	${env.build_flags}
; 	-DARDUINO_ARCH_AVR

[env:nanoatmega328_new]
platform = atmelavr
board = nanoatmega328new 	; mini-usb
build_flags =
	${env.build_flags}
	-DARDUINO_ARCH_AVR