#ifndef GLOBALS_H
#define GLOBALS_H

#pragma once

#define GLASSES 7



#define MICROSWITCH_1_PIN_COM 4
#define MICROSWITCH_2_PIN_COM 6
#define MICROSWITCH_3_PIN_COM 7
#define MICROSWITCH_4_PIN_COM 8
#define MICROSWITCH_5_PIN_COM 9
#define MICROSWITCH_6_PIN_COM 10
#define MICROSWITCH_7_PIN_COM 11
#define MICROSWITCH_8_PIN_COM 12



#endif